FB-43: layout fix
DiRaiks/football_planner pull request #14
Opened 2019-10-23 08:54 UTC by evpirogov

2019-10-23 09:43 UTC, DiRaiks requested changes

2019-10-23 09:43 UTC, DiRaiks commented on src/components/reusableComponents/eventForm/EventForm.vue
> +            height: 100%;
маржин был у элемента который может быть/может не быть. Нет эелемента - нет маржина. Сейчас маржин присутствует всегда. В чем выгода?

2019-10-23 09:43 UTC, DiRaiks commented on src/components/reusableComponents/table/Table.vue
> +        // padding: 15px 20px;
коммент

2019-10-23 09:43 UTC, DiRaiks commented on src/components/reusableComponents/table/Table.vue
> +                border-spacing: 5px;
не мало? Может лучше для колонки с именами игрков сделать максимальную ширину?

2019-10-23 09:43 UTC, DiRaiks commented on src/components/reusableComponents/table/TableLine.vue
> +            padding: 0px 10px;
0px -> 0

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/allEvents/AllEvents.vue
> +        // padding: 20px;
коммент

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/allEvents/AllEvents.vue
> +            // text-align: center;
коммент

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                width: 500px;
+ пустую строку перед новым классом

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                    padding: 0px 0px 200px;
0px -> 0

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                padding: 0px;
0px -> 0

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                }
0px -> 0

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                    padding: 0px 0px 200px;
зачем паддин снизу 200пх?

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                    padding: 0px 0px 200px;
зачем паддинг снизу 200?

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/eventPage/EventPage.vue
> +            padding: 0px 0px 200px;
0px ->0

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/eventPage/EventPage.vue
> +            padding: 0px 0px 200px;
и выше

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/eventPage/EventPage.vue
> +            margin-top: 0px;
0

2019-10-23 09:43 UTC, DiRaiks commented on src/components/routeComponents/allEvents/AllEvents.vue
> +            padding: 10px 25px 0px;
0

2019-10-24 11:00 UTC, evpirogov commented on src/components/reusableComponents/eventForm/EventForm.vue
> +            height: 100%;
Чтобы на маленьком разрешении хорошо выглядело, если обе кнопки не помещаются:
![image](https://user-images.githubusercontent.com/54399936/67462626-9fc3d380-f648-11e9-9656-c8a58dfe0b4e.png)

2019-10-24 11:00 UTC, evpirogov commented on src/components/reusableComponents/table/Table.vue
> +        // padding: 15px 20px;
Убрал

2019-10-24 11:00 UTC, evpirogov commented on src/components/reusableComponents/table/Table.vue
> +                border-spacing: 5px;
Да вроде норм выглядит. На маленьких экранах не нужны большие отступы. В форме редактирования события тоже по 5px с каждой стороны. 
![image](https://user-images.githubusercontent.com/54399936/67463094-78b9d180-f649-11e9-8618-2aab869780f6.png)

2019-10-24 11:00 UTC, evpirogov commented on src/components/reusableComponents/table/TableLine.vue
> +            padding: 0px 10px;
Поправил

2019-10-24 11:00 UTC, evpirogov commented on src/components/routeComponents/allEvents/AllEvents.vue
> +        // padding: 20px;
Поправил

2019-10-24 11:00 UTC, evpirogov commented on src/components/routeComponents/allEvents/AllEvents.vue
> +            // text-align: center;
Поправил

2019-10-24 11:00 UTC, evpirogov commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                padding: 0px;
Поправил

2019-10-24 11:00 UTC, evpirogov commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                    padding: 0px 0px 200px;
0 поправил.
200px на мобилках, чтобы добавление друзей нормально отображалось. Тоесть ты можешь сразу достаточно проскролить вниз, чтобы комфортно добавлять новых друзей. Иначе придется после каждого нового друга - подскроивать (потому что форма заходит за нижнюю границу экрана)

2019-10-24 11:00 UTC, evpirogov commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                    padding: 0px 0px 200px;
200px как раз комфортно на +3 друга

2019-10-24 11:00 UTC, evpirogov commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                width: 500px;
Добавил

2019-10-24 11:00 UTC, evpirogov commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                }
Исправил

2019-10-24 11:00 UTC, evpirogov commented on src/components/routeComponents/allEvents/AllEvents.vue
> +            padding: 10px 25px 0px;
Поправил

2019-10-24 11:01 UTC, evpirogov commented on src/components/routeComponents/eventPage/EventPage.vue
> +            margin-top: 0px;
Поправил

2019-10-24 11:01 UTC, evpirogov commented on src/components/routeComponents/eventPage/EventPage.vue
> +            padding: 0px 0px 200px;
Поправил

2019-10-24 11:02 UTC, evpirogov commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                    padding: 0px 0px 200px;
Здесь убрал. Задвоение. Выше объяснил логику

2019-10-24 11:03 UTC, DiRaiks commented on src/components/reusableComponents/eventForm/EventForm.vue
> +            height: 100%;
а, понял. Можно еще было бы уменьшить кнопку редактировать. Мб переименовать в просто "редактировать".

2019-10-24 11:05 UTC, DiRaiks commented on src/components/routeComponents/allEvents/AllEvents.vue
> +                    padding: 0px 0px 200px;
такое себе решение) Можно будет придумать что-нибудь с автоподскроллом.

2019-10-24 11:07 UTC, DiRaiks commented on src/components/reusableComponents/eventForm/EventForm.vue
> +            height: 100%;
тогда кнопки будут рядом на всех разрешениях. Но пока норм

2019-10-24 11:07 UTC, evpirogov commented on src/components/reusableComponents/eventForm/EventForm.vue
> +            height: 100%;
Можно просто - "Применить" это шаблонная кнопка ее поведение всем знакомо?
Но может стоит оставить логику переноса? Потом решим поменять текст и все сломается.

2019-10-24 11:08 UTC, DiRaiks commented on src/components/reusableComponents/table/Table.vue
> +                border-spacing: 5px;
Окей, убедил)

2019-10-24 11:11 UTC, DiRaiks approved these changes

2019-10-24 11:12 UTC, merged